create table if not exists public.people (
  id text primary key,
  first_name text not null,
  last_name text not null
);

create table if not exists public.checkins (
  id bigint generated by default as identity primary key,
  person_id text not null references public.people (id) on delete cascade,
  first_name text not null,
  last_name text not null,
  checked_in_at timestamptz not null default now(),
  notes text not null default ''
);
